CarRent/Areas/Admin/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data;
using Entities;
using CarRent.Tools;

namespace CarRent.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CarsController : Controller
    {
        private readonly DatabaseContext _context;

        public CarsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Admin/Cars
        public async Task<IActionResult> Index()
        {
            var databaseContext = _context.Cars.Include(c => c.Category).Include(c => c.Brand);


            return View(await databaseContext.ToListAsync());
        }

        // GET: Admin/Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Admin/Cars/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name");
            return View();
        }




        // POST: Admin/Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car, IFormFile? Image)
        {
            if (ModelState.IsValid)
            {
                car.Image = await FileHelper.FileLoaderAsync(Image);
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", car.CategoryId);
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", car.BrandId);
            return View(car);
        }



        // GET: Admin/Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }

            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", car.CategoryId);
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", car.BrandId); // Burada "Name" kullanılarak marka adları gösterilecek
            return View(car);
        }


        // POST: Admin/Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Image,IsActive,IsHome,Stock,Price,CategoryId,BrandId,MotorGucu,Model,GearName")] Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", car.CategoryId);
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", car.BrandId);
            return View(car);
        }

        // GET: Admin/Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Admin/Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Cars.FindAsync(id);
            if (car != null)
            {
                _context.Cars.Remove(car);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Cars.Any(e => e.Id == id);
        }
    }
}

CarRent/Controllers/CarsController.cs
using Data;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarRent.Controllers
{
    public class CarsController : Controller
    {
        private readonly DatabaseContext _dbContext;

        public CarsController(DatabaseContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var years = await _dbContext.Cars.Select(c => c.Model).Distinct().ToListAsync();
            var brands = await _dbContext.Cars.Select(c => c.Brand.Name).Distinct().ToListAsync();
            var categories = await _dbContext.Cars.Select(c => c.Category.Name).Distinct().ToListAsync();
            var prices = await _dbContext.Cars.Select(c => c.Price).Distinct().ToListAsync();

            ViewBag.Models = years ?? new List<string>();
            ViewBag.Brands = brands ?? new List<string>();
            ViewBag.Categories = categories ?? new List<string>();
            ViewBag.Prices = prices ?? new List<decimal>();

            var databaseContext = _dbContext.Cars
                                            .Include(p => p.Category)
                                            .Include(p => p.Brand);

            return View(await databaseContext.ToListAsync());
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var model = await _dbContext.Cars
                .Where(x => x.Id == id && x.IsActive)
                .Include(x => x.Category)
                .Include(x => x.Brand)
                .Include(x => x.Comments)
                .ThenInclude(c => c.User) // Yorumlarla birlikte kullanıcı bilgilerini de dahil et
                .FirstOrDefaultAsync();

            if (model == null)
            {
                return NotFound();
            }

            // Kullanıcının oturum durumunu ViewBag'e ekleyin
            ViewBag.IsLoggedIn = HttpContext.Session.GetInt32("IsLoggedIn") == 1;

            // Yorumları ViewBag'e ekleyin
            ViewBag.Comments = model.Comments ?? new List<Comment>();

            return View(model);
        }

        [HttpPost]
       
        public ActionResult Comment(Comment data)
        {
            // Kullanıcı ID'sini oturumdan alın
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                // Kullanıcı oturum açmamışsa hata döndür
                return Unauthorized();
            }

            data.UserId = userId.Value; // Yorum nesnesine kullanıcı ID'sini atayın
            data.Date = DateTime.Now;

            _dbContext.Comments.Add(data);
            _dbContext.SaveChanges();

            return RedirectToAction("Detail", new { id = data.CarId });
        }


        public async Task<IActionResult> Search(string model, string brand, string category, string gearname, string q)
        {
            var query = _dbContext.Cars.Include(c => c.Brand).Include(c => c.Category).AsQueryable();

            if (!string.IsNullOrEmpty(model) && model != "default")
            {
                query = query.Where(c => c.Model.ToLower() == model.ToLower());
            }

            if (!string.IsNullOrEmpty(brand) && brand != "default")
            {
                query = query.Where(c => c.Brand.Name.ToLower() == brand.ToLower());
            }

            if (!string.IsNullOrEmpty(category) && category != "default")
            {
                query = query.Where(c => c.Category.Name.ToLower() == category.ToLower());
            }

            if (!string.IsNullOrEmpty(gearname) && gearname != "default")
            {
                query = query.Where(c => c.GearName.ToLower() == gearname.ToLower());
            }

            if (!string.IsNullOrEmpty(q))
            {
                var lowercaseQuery = q.ToLower();
                query = query.Where(c => c.Model.ToLower().Contains(lowercaseQuery) ||
                                         c.Brand.Name.ToLower().Contains(lowercaseQuery) ||
                                         c.Category.Name.ToLower().Contains(lowercaseQuery) ||
                                         c.GearName.ToLower().Contains(lowercaseQuery));
            }

            var cars = await query.ToListAsync();

            return View("Search", cars);
        }
    }
}

CarRent/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

using Entities;
using Data;
using System.Net;

namespace CarRent.Controllers
{
    public class CartController : Controller
    {
        private readonly DatabaseContext _dbContext;

        public CartController(DatabaseContext dbContext)
        {
            _dbContext = dbContext;
        }
        [HttpPost]
        public async Task<IActionResult> RentCar(int carId, DateTime startDate, DateTime endDate)
        {
            var car = await _dbContext.Cars.FirstOrDefaultAsync(c => c.Id == carId);
            if (car == null)
            {
                return NotFound();
            }

            // Kiralama süresini hesapla
            TimeSpan rentalPeriod = endDate - startDate;

            // Toplam ücreti hesapla
            decimal totalPrice = car.Price * (decimal)rentalPeriod.TotalDays;

            // Kiralama işlemi için gerekli bilgileri ViewBag'e ekle
            ViewBag.CarId = carId;
            if (car.Brand != null) // Null kontrolü
            {
                ViewBag.CarName = $"{car.Brand.Name} {car.Name}";
            }
            else
            {
                ViewBag.CarName = $"{car.Name}";
            }
            ViewBag.DailyPrice = car.Price;
            ViewBag.StartDate = startDate;
            ViewBag.EndDate = endDate;
            ViewBag.TotalPrice = totalPrice; // Toplam ücreti ViewBag'e ekle

            return View("RentCarDetails");
        }


        [HttpPost]
        public async Task<IActionResult> ConfirmRent(int carId, DateTime startDate, DateTime endDate, string cardNo, string cvv)
        {
            // Retrieve user information from session
            var userId = HttpContext.Session.GetInt32("UserId");
            var user = await _dbContext.Users.FindAsync(userId);
            if (userId == null || user == null)
            {
                return Unauthorized(); // User not authenticated
            }

            // Retrieve car information
            var car = await _dbContext.Cars
                .Include(c => c.Brand) // Include the brand information
                .FirstOrDefaultAsync(c => c.Id == carId);
            if (car == null)
            {
                return NotFound(); // Car not found
            }

            // Create order
            var order = new Order
            {
                CarId = car.Id,
                UserId = userId.Value,
                RentStartDate = startDate,
                RentEndDate = endDate,
                CardNo = cardNo,
                CVV = cvv,
                Address = user.Address,
                Email = user.Email, // Populate with user's email
                Name = user.Name, // Populate with user's first name
                Surname = user.Surname, // Populate with user's last name
                Phone = user.Phone, // Populate with user's phone number
                CreateDate = DateTime.Now,
                 CarName = car.Brand != null ? $"{car.Brand.Name} {car.Name}" : car.Name,
                Status = OrderStatus.Beklemede

            };

            _dbContext.Orders.Add(order);
            await _dbContext.SaveChangesAsync();

            

            return View("RentCarConfirmation");
        }



    }
}

CarRent/Views/Cars/Detail.cshtml
@model Car
@{
    ViewData["Title"] = "Car Detail";
}

<br />
<br />
<br />
<br />
<br />
<br />
<section class="py-5">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 align-items-center mb-5">
            <div class="col-md-6">
                <img class="card-img-top mb-5 mb-md-0" src="/Images/@Model.Image" alt="@Model.Image">
            </div>
            <div class="col-md-6">
                <h1 class="display-4 fw-bolder">@Model.Brand.Name @Model.Name</h1>
                <div class="small mb-3">@Model.Model Model</div>
                <div class="small mb-3">@Model.MotorGucu HP</div>
                <div class="small mb-3">@Model.GearName Vites</div>
                <div class="fs-5 mb-5">
                    <span class="text-decoration-line-through">@Model.Price</span>
                    @if (ViewBag.IsLoggedIn)
                    {
                        <form class="rent-form" asp-controller="Cart" asp-action="RentCar" method="post">
                            <input type="hidden" name="carId" value="@Model.Id" />
                            <div class="form-group">
                                <label for="startDate">Başlangıç Tarihi</label>
                                <input type="date" id="startDate" name="startDate" required>
                            </div>
                            <div class="form-group">
                                <label for="endDate">Bitiş Tarihi</label>
                                <input type="date" id="endDate" name="endDate" required>
                            </div>
                            <button type="submit" class="btn btn-primary ms-auto rounded-pill px-4 py-2">Aracı Kirala</button>
                        </form>
                    }
                    else
                    {
                        <p>Aracı Kiralamak İçin Giriş Yapmalısın <a asp-controller="Account" asp-action="Login">giriş yapmalısınız</a>.</p>
                    }
                </div>
                <br />
                <h5>Araç Özellikleri</h5>
                <p class="lead">@Model.Description</p>
            </div>
        </div>

        @if (ViewBag.IsLoggedIn)
        {
            <div class="col-lg-4">
                <h5>Yorum Ekle</h5>
                <form class="comment-form" asp-controller="Cars" asp-action="Comment" method="post">
                    <div class="form-group">
                        <label for="commentContents">Yorumunuz</label>
                        <textarea class="form-control" id="commentContents" name="Contents" rows="3" required></textarea>
                    </div>
                    <input type="hidden" name="CarId" value="@Model.Id" />
                    <button type="submit" class="btn btn-primary">Gönder</button>
                </form>
            </div>
        }
        else
        {
            <p>Yorum ekleyebilmek için <a asp-controller="Account" asp-action="Login">giriş yapmalısınız</a>.</p>
        }

        <div class="col-lg-8 mt-5">
            <h5>Yorumlar</h5>
            @foreach (var comment in ViewBag.Comments)
            {
                <div class="comment-container">
                    <div class="comment-author">@comment.User.Name:</div>
                    <div class="comment-content">@comment.Contents</div>
                    <div class="comment-date">@comment.Date.ToString("g")</div>
                </div>
            }
        </div>
    </div>
</section>

CarRent/Views/Cars/Search.cshtml
@model IEnumerable<Car>

<div class="container">
   <br />
    <br />
    <br />
    <br />
     <br />
      <br />
       <br />
        <br />
       




    <div class="row">
        @foreach (var car in Model)
        {
            <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                <a href="/Cars/Detail/@car?.Id" class="text-decoration-none">
                <!-- mb-4 sınıfı alt boşluk ekler -->
                <div class="single-featured-cars">
                    <div class="featured-img-box">
                        <div class="featured-cars-img">
                            <img src="~/Images/@car.Image" class="img-fluid car-img" alt="@car.Model">
                        </div>
                        <div class="featured-model-info">
                            <p>
                                @car.Model
                                <span class="featured-hp-span">@car.MotorGucu HP</span>
                                @car.GearName
                            </p>
                        </div>
                    </div>
                    <div class="featured-cars-txt">
                        <h2><a href="#">@car.Brand.Name @car.Name</a></h2>
                        <h3>@car.Price ₺</h3>
                        <p>
                            @car.Description
                        </p>
                    </div>
                </div>
                </a>
            </div>
        }
    </div>
</div>